version: "3"

volumes:
  paymongo_local_postgres_data: {}
  paymongo_local_postgres_data_backups: {}

services:
  nextjs:
    build:
      context: .
      dockerfile: ./lib/serverless/compose/nextjs/prod/Dockerfile
    depends_on:
      - redis
    ports:
      - "80:80"

  redis:
    image: redis:6
    container_name: paymongo_local_redis
